.\" $OpenBSD$
.\" Copyright (c) 2023 Ted Bullock <tbullock@comlore.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt EVENT_BASE_GET_METHOD 3
.Os
.Sh NAME
.Nm event_base_get_method ,
.Nm event_get_method ,
.Nm event_get_version
.Nd return library parameters
.Sh SYNOPSIS
.In event.h
.Ft "const char *"
.Fn event_base_get_method "struct event_base *base"
.Ft "const char *"
.Fn event_get_method void
.Ft "const char *"
.Fn event_get_version void
.Sh DESCRIPTION
The
.Fn event_base_get_method
function returns the notification method registered to the
.Vt event_base
structure by
.Xr event_base_new 3 .
This is the underlying mechanism used by the event library to monitor file
descriptor and signal events.
On
.Ox
the default method is
.Xr kqueue 2
however
.Xr poll 2
and
.Xr select 2
are also supported.
The function checks
.Va base
is not
.Dv NULL
with
.Xr assert 3 .
.Pp
.Fn event_get_method
is similar to
.Fn event_base_get_method ,
and requires the library be initialized with
.Xr event_init 3 .
.Pp
.Fn event_get_version
returns the library version in use.
.Sh RETURN VALUES
The functions
.Fn event_base_get_method
and
.Fn event_get_method
return an ASCII string representing the method used to dispatch events.
.Pp
.Fn event_get_version
returns an ASCII string containing the event library version in use.
.Sh SEE ALSO
.Xr event_base_new 3
.Sh HISTORY
.Fn event_base_get_method
first appeared in libevent-1.4.3 and has been available since
.Ox 4.8 .
.Pp
.Fn event_get_version
and
.Fn event_get_method
first appeared in libevent-1.0c and have been available since
.Ox 3.8 .
.Sh AUTHORS
.An Nick Mathewson
created
.Fn event_get_version
and
.Fn event_get_method .
.Pp
.An -nosplit
.Fn event_base_get_method
was written by
.An Springande Ulv .
.Pp
This manual page was written by
.An Ted Bullock Aq Mt tbullock@comlore.com .
