.\" $OpenBSD$
.\" Copyright (c) 2023 Ted Bullock <tbullock@comlore.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd $Mdocdate$
.Dt EVENT_REINIT 3
.Os
.Sh NAME
.Nm event_reinit
.Nd reinitialize the event library after a fork
.Sh SYNOPSIS
.In event.h
.Ft int
.Fn event_reinit "struct event_base *base"
.Sh DESCRIPTION
The function
.Fn event_reinit
is used to reinitialize the event library in a child process after a call to
.Xr fork 2 .
The function reinitializes the internal state of the event library, including
the event queues and events registered with the kernel notification method.
See
.Xr event_base_new 3
for an explanation of kernel notification methods in the event library.
.Pp
The function
.Fn event_reinit
takes a single argument, a pointer to an
.Vt event_base
structure initialized by
.Xr event_init 3
or
.Xr event_base_new 3 .
.Pp
The behaviour is undefined if
.Va base
is
.Dv NULL .
.Sh RETURN VALUES
On success, the function returns 0.
If one or more events fail to reinitialize, the function returns -1.
.Pp
Fatal error conditions will
.Em not
return.
.Sh DIAGNOSTICS
The event library relies on its own system to issue messages via callbacks via
.Xr event_set_log_callback 3 .
The function
.Fn event_reinit
can potentially cause the following fatal error messages to be sent to the log
callback:
.Bl -tag -width Ds
.It Dq event_base_reinit: could not reinitialize event mechanism
Failed to reinitialize the kernel notification method.
.It Dq event_queue_remove: Em @p Po fd Em @d Pc not on queue Em @x
The internal event library function
.Fn event_queue_remove
failed to clear an event queue.
The message format will be populated as follows:
.Bl -hyphen -compact -width 1n
.It
.Em @p :
Event structure memory address in hexadecimal format.
.It
.Em @d :
File descriptor in decimal format.
.It
.Em @x :
Event queue number in hexadecimal format corresponding to either
.Dv EVLIST_INSERTED 0x02
or
.Dv EVLIST_ACTIVE 0x08 .
.El
.It Dq event_queue_remove: unknown queue Em @q
The internal event function
.Fn event_queue_remove
encountered an unknown queue number, indicated by
.Em @q
in hexadecimal format.
.El
.Sh SEE ALSO
.Xr fork 2 ,
.Xr event_base_new 3 ,
.Xr event_set_log_callback 3
.Sh HISTORY
The function
.Fn event_reinit
was first released in libevent-1.4.3 and included in
.Ox 4.8 .
.Sh AUTHORS
The event library
was written by
.An -nosplit
.An Niels Provos
and
.An Nick Mathewson .
.Pp
This manual was written by
.An Ted Bullock Aq Mt tbullock@comlore.com .
